### ISSUE TITLE
the activation mail is not working, and an another bug.

### ISSUE THREAD

**Issue by youssefhafez** [ah450/runner-frontend#3]
i have tried to log in to my account @ evaluator.in but i got the error : Account Inactive, please check your spam folder. A kind remark i have pressed on resend activation mail in attempt to receive it but ends up in failure, also i have checked both my spam folder , and inbox.

also i would like to report a bug that happen when i have tried to upload my project, each time I've tried to upload; the project the page stuck on the animation of loading (the blue one) as if it have fallen in infinite loop, so i have tried to log out in attempt to solve the problem. after that I wasn't to able to access my account.

**Comment by amrdraz** [comment]
the mail server was down earlier this morning due to server restart
we got it working and you should be able to recieve your activation email

as for the later bug, it is not a bug that the system displays loading, as merely the case is that you need to refresh the submission's page after about 5 seconds (giving time for the submission to process)

**Comment by youssefhafez** [comment]
please note that it does not open even after log out and log in and even after resubmitting.
![error](https://cloud.githubusercontent.com/assets/11260591/6460568/e24ae6f8-c1a0-11e4-872e-432aa79f0d3c.png)

**Comment by amrdraz** [comment]
we will rerun old submissions since the bug, but new submissions should
work fine

**Comment by youssefhafez** [comment]
Thanks.
